// Filesystem persistence for generated MISMO documents.
//
// All I/O for the module lives here so map.ts and build.ts stay pure and
// testable without a tmpdir.
//
// Deployment note: this app runs under Phusion Passenger on cPanel, which has
// a persistent filesystem. The default storage root is a SIBLING of the app
// directory, never under public/, so Passenger cannot serve these documents.

import { createHash } from "node:crypto";
import { mkdir, open, rename, writeFile } from "node:fs/promises";
import path from "node:path";

export interface StoredMismoFile {
  /** Absolute path on disk. */
  path: string;
  /** Path relative to the storage root — what goes in the database. */
  relativePath: string;
  bytes: number;
  sha256: string;
}

/** Deny-all rule, in case the storage root is ever relocated under public_html. */
const HTACCESS_BODY = [
  "# Generated by the Alta application pipeline.",
  "# These are mortgage applications. They must never be web-served.",
  "Require all denied",
  "<IfModule !mod_authz_core.c>",
  "  Order allow,deny",
  "  Deny from all",
  "</IfModule>",
  "",
].join("\n");

export function resolveStorageRoot(): string {
  const configured = process.env.MISMO_STORAGE_DIR;
  if (configured && configured.trim() !== "") return path.resolve(configured.trim());
  return path.resolve(process.cwd(), "..", "storage", "mismo");
}

/** Strip anything that has no business in a filename. */
function safeSegment(value: string): string {
  const cleaned = value.replace(/[^A-Za-z0-9._-]/g, "");
  return cleaned === "" ? "UNKNOWN" : cleaned;
}

/** 2026-09-08T14:30:12.345Z -> 20260908T143012Z */
function compactTimestamp(iso: string): string {
  const date = new Date(iso);
  const source = Number.isNaN(date.getTime()) ? new Date() : date;
  return source.toISOString().replace(/[-:]/g, "").replace(/\.\d+/, "");
}

export function buildRelativePath(referenceNumber: string, submittedAt: string): string {
  const date = new Date(submittedAt);
  const source = Number.isNaN(date.getTime()) ? new Date() : date;
  const year = String(source.getUTCFullYear());
  const month = String(source.getUTCMonth() + 1).padStart(2, "0");
  const name = `${safeSegment(referenceNumber)}-${compactTimestamp(submittedAt)}.xml`;
  return path.join(year, month, name);
}

async function ensureDenyFile(root: string): Promise<void> {
  try {
    // wx: never clobber an existing rule, and no read needed to check.
    await writeFile(path.join(root, ".htaccess"), HTACCESS_BODY, { flag: "wx" });
  } catch (err) {
    const code = (err as NodeJS.ErrnoException)?.code;
    if (code !== "EEXIST") {
      console.warn("Could not write MISMO storage .htaccess:", code ?? err);
    }
  }
}

/**
 * Write a MISMO document atomically: full write and fsync to a temp file in
 * the destination directory, then rename over the target. A crash mid-write
 * cannot leave a truncated 1003 behind.
 */
export async function writeMismoFile(
  xml: string,
  input: { referenceNumber: string; submittedAt: string }
): Promise<StoredMismoFile> {
  const root = resolveStorageRoot();
  const relativePath = buildRelativePath(input.referenceNumber, input.submittedAt);
  const absolutePath = path.join(root, relativePath);

  await mkdir(path.dirname(absolutePath), { recursive: true });
  await ensureDenyFile(root);

  const payload = Buffer.from(xml, "utf8");
  const tempPath = `${absolutePath}.${process.pid}.tmp`;

  const handle = await open(tempPath, "wx");
  try {
    await handle.writeFile(payload);
    await handle.sync();
  } finally {
    await handle.close();
  }
  await rename(tempPath, absolutePath);

  return {
    path: absolutePath,
    relativePath,
    bytes: payload.byteLength,
    sha256: createHash("sha256").update(payload).digest("hex"),
  };
}
