// Persistence for generated MISMO documents.
//
// All I/O for the module lives here so map.ts and build.ts stay pure and
// testable without a tmpdir.
//
// Two backends, chosen by environment:
//
//   Vercel Blob  when the store is connected to the project. This is
//                production. The site deploys to Vercel, whose function
//                filesystem is read-only and discarded after each request,
//                so a file on disk there would be lost before the response
//                was sent. Blobs are written with access: "private" — there
//                is no public URL for a mortgage application.
//
//                Two credential styles exist. Newer stores inject
//                BLOB_STORE_ID and the SDK authenticates with the OIDC token
//                Vercel supplies to every function invocation; older stores
//                inject BLOB_READ_WRITE_TOKEN. Either one means "use Blob".
//
//   Local disk   otherwise. Local development and tests. The root is a
//                sibling of the app directory, never under public/.

import { createHash } from "node:crypto";
import { mkdir, open, rename, writeFile } from "node:fs/promises";
import path from "node:path";
import { put } from "@vercel/blob";

export interface StoredMismoFile {
  /**
   * Where the document lives. A blob pathname in production, an absolute
   * filesystem path locally.
   */
  path: string;
  /** Backend-relative key — what goes in the database. Same in both backends. */
  relativePath: string;
  /** Blob URL when stored in Vercel Blob; absent on disk. Private — not a link. */
  url?: string;
  bytes: number;
  sha256: string;
}

export type MismoBackend = "blob" | "disk";

export function mismoBackend(): MismoBackend {
  return process.env.BLOB_READ_WRITE_TOKEN || process.env.BLOB_STORE_ID ? "blob" : "disk";
}

/** Strip anything that has no business in a filename. */
function safeSegment(value: string): string {
  const cleaned = value.replace(/[^A-Za-z0-9._-]/g, "");
  return cleaned === "" ? "UNKNOWN" : cleaned;
}

/** 2026-09-08T14:30:12.345Z -> 20260908T143012Z */
function compactTimestamp(iso: string): string {
  const date = new Date(iso);
  const source = Number.isNaN(date.getTime()) ? new Date() : date;
  return source.toISOString().replace(/[-:]/g, "").replace(/\.\d+/, "");
}

/**
 * Year/month/filename, with forward slashes regardless of platform: this is
 * a storage key, not a filesystem path, and Blob pathnames use "/".
 */
export function buildRelativePath(referenceNumber: string, submittedAt: string): string {
  const date = new Date(submittedAt);
  const source = Number.isNaN(date.getTime()) ? new Date() : date;
  const year = String(source.getUTCFullYear());
  const month = String(source.getUTCMonth() + 1).padStart(2, "0");
  const name = `${safeSegment(referenceNumber)}-${compactTimestamp(submittedAt)}.xml`;
  return `${year}/${month}/${name}`;
}

function digest(payload: Buffer): string {
  return createHash("sha256").update(payload).digest("hex");
}

// ---- Vercel Blob ------------------------------------------------------------

const BLOB_PREFIX = "mismo";

async function writeToBlob(payload: Buffer, relativePath: string): Promise<StoredMismoFile> {
  const pathname = `${BLOB_PREFIX}/${relativePath}`;
  const result = await put(pathname, payload, {
    access: "private",
    contentType: "application/xml",
    addRandomSuffix: false,
    // Write-once. A second document under the same reference number is a
    // bug worth surfacing, not silently replacing.
    allowOverwrite: false,
  });
  return {
    path: result.pathname,
    relativePath,
    url: result.url,
    bytes: payload.byteLength,
    sha256: digest(payload),
  };
}

// ---- Local disk -------------------------------------------------------------

/** Deny-all rule, in case the storage root is ever placed under a web root. */
const HTACCESS_BODY = [
  "# Generated by the Alta application pipeline.",
  "# These are mortgage applications. They must never be web-served.",
  "Require all denied",
  "<IfModule !mod_authz_core.c>",
  "  Order allow,deny",
  "  Deny from all",
  "</IfModule>",
  "",
].join("\n");

export function resolveStorageRoot(): string {
  const configured = process.env.MISMO_STORAGE_DIR;
  if (configured && configured.trim() !== "") return path.resolve(configured.trim());
  return path.resolve(process.cwd(), "..", "storage", "mismo");
}

async function ensureDenyFile(root: string): Promise<void> {
  try {
    // wx: never clobber an existing rule, and no read needed to check.
    await writeFile(path.join(root, ".htaccess"), HTACCESS_BODY, { flag: "wx" });
  } catch (err) {
    const code = (err as NodeJS.ErrnoException)?.code;
    if (code !== "EEXIST") {
      console.warn("Could not write MISMO storage .htaccess:", code ?? err);
    }
  }
}

/**
 * Atomic: full write and fsync to a temp file in the destination directory,
 * then rename over the target. A crash mid-write cannot leave a truncated
 * 1003 behind.
 */
async function writeToDisk(payload: Buffer, relativePath: string): Promise<StoredMismoFile> {
  const root = resolveStorageRoot();
  const absolutePath = path.join(root, ...relativePath.split("/"));

  await mkdir(path.dirname(absolutePath), { recursive: true });
  await ensureDenyFile(root);

  const tempPath = `${absolutePath}.${process.pid}.tmp`;
  const handle = await open(tempPath, "wx");
  try {
    await handle.writeFile(payload);
    await handle.sync();
  } finally {
    await handle.close();
  }
  await rename(tempPath, absolutePath);

  return {
    path: absolutePath,
    relativePath,
    bytes: payload.byteLength,
    sha256: digest(payload),
  };
}

// ---- Public -----------------------------------------------------------------

export async function writeMismoFile(
  xml: string,
  input: { referenceNumber: string; submittedAt: string }
): Promise<StoredMismoFile> {
  const relativePath = buildRelativePath(input.referenceNumber, input.submittedAt);
  const payload = Buffer.from(xml, "utf8");
  return mismoBackend() === "blob"
    ? writeToBlob(payload, relativePath)
    : writeToDisk(payload, relativePath);
}
