import { NextResponse } from "next/server";
import { promises as fs } from "fs";
import path from "path";

// Capture the process start time once, on module load.
// Each Node.js restart resets this — useful for spotting whether
// the app actually restarted after a deploy.
const PROCESS_STARTED_AT = new Date().toISOString();

interface BuildInfo {
  buildId: string | null;
  buildTime: string | null;
}

/**
 * Read Next.js's BUILD_ID file. This is a unique hash regenerated by
 * `next build` every time. If two HTTP requests return DIFFERENT BUILD_IDs,
 * Hostinger's deploy pipeline is creating a new build mid-request which
 * would explain stale-chunk 404s.
 */
async function readBuildInfo(): Promise<BuildInfo> {
  try {
    const buildIdPath = path.join(process.cwd(), ".next", "BUILD_ID");
    const [content, stat] = await Promise.all([
      fs.readFile(buildIdPath, "utf-8"),
      fs.stat(buildIdPath),
    ]);
    return {
      buildId: content.trim(),
      buildTime: stat.mtime.toISOString(),
    };
  } catch {
    return { buildId: null, buildTime: null };
  }
}

/**
 * Try to read git commit info. Only works if .git directory was deployed
 * to the server (true with cPanel "Git Version Control" auto-deploys).
 */
async function readGitInfo(): Promise<{ sha: string | null; branch: string | null }> {
  try {
    const headPath = path.join(process.cwd(), ".git", "HEAD");
    const head = (await fs.readFile(headPath, "utf-8")).trim();

    // HEAD points either to a branch ref ("ref: refs/heads/main")
    // or directly to a commit SHA (detached HEAD).
    if (head.startsWith("ref: ")) {
      const refPath = head.slice(5).trim();
      const branch = refPath.split("/").pop() || null;
      const sha = (
        await fs.readFile(path.join(process.cwd(), ".git", refPath), "utf-8")
      ).trim();
      return { sha, branch };
    }
    return { sha: head, branch: null };
  } catch {
    return { sha: null, branch: null };
  }
}

export async function GET() {
  const [build, git] = await Promise.all([readBuildInfo(), readGitInfo()]);
  const uptimeSeconds = Math.round(process.uptime());

  // Configuration health — does NOT leak any secret values, only presence.
  const config = {
    db: Boolean(process.env.DB_HOST && process.env.DB_USER && process.env.DB_NAME),
    smtp: Boolean(process.env.SMTP_HOST && process.env.SMTP_USER && process.env.SMTP_PASS),
    crm: Boolean(process.env.CRM_API_URL && process.env.CRM_API_KEY),
    notificationEmail: Boolean(process.env.NOTIFICATION_EMAIL),
    siteUrl: process.env.NEXT_PUBLIC_SITE_URL || null,
  };

  return NextResponse.json(
    {
      ok: true,
      build: {
        nextBuildId: build.buildId,
        nextBuildTime: build.buildTime,
        gitSha: git.sha,
        gitShaShort: git.sha ? git.sha.slice(0, 7) : null,
        gitBranch: git.branch,
      },
      process: {
        startedAt: PROCESS_STARTED_AT,
        uptimeSeconds,
        nodeVersion: process.version,
        nodeEnv: process.env.NODE_ENV || "development",
      },
      config,
      serverTime: new Date().toISOString(),
    },
    {
      headers: {
        // Never cache this endpoint — we need fresh data every time
        // to diagnose stale-deploy issues.
        "Cache-Control": "no-store, no-cache, must-revalidate",
      },
    }
  );
}
